# Generated by Django 4.2.6 on 2023-10-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorations', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
                ('drinks', models.BooleanField(default=False)),
                ('photos_filming', models.BooleanField(default=False)),
                ('parties', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.BigIntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('attendes', models.IntegerField()),
                ('expected_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.preferencestype')),
            ],
        ),
    ]
