# Generated by Django 4.2.6 on 2023-10-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.BigIntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('attendes', models.IntegerField()),
                ('decorations', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
                ('drinks', models.BooleanField(default=False)),
                ('photos_filming', models.BooleanField(default=False)),
                ('parties', models.BooleanField(default=False)),
                ('expected_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_status', models.CharField(choices=[('pending_senior_approval', 'Pending Senior Customer Service Approval'), ('pending_finance_approval', 'Pending Finance Manager Approval'), ('pending_admin_approval', 'Pending Administration Manager Approval'), ('pending_senior_final_approval', 'Pending Senior Customer Service Final Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_senior_approval', max_length=40)),
            ],
        ),
    ]
