# Generated by Django 4.2.6 on 2023-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='preferences',
        ),
        migrations.AddField(
            model_name='event',
            name='decorations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='drinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='parties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='photos_filming',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PreferencesType',
        ),
    ]
