# Generated by Django 4.2.6 on 2023-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='_status',
            field=models.CharField(choices=[('created', 'Created'), ('senior_approval', 'Senior Approval'), ('finance_approval', 'Finance Approval'), ('admin_approval', 'Admin Approval'), ('senior_approval_last', 'Senior Approval (Last)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='created', max_length=20),
        ),
    ]
