# Generated by Django 4.2.6 on 2023-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_status_event__status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='_status',
            field=models.CharField(choices=[('pending_senior_approval', 'Pending Senior Customer Service Approval'), ('pending_finance_approval', 'Pending Finance Manager Approval'), ('pending_admin_approval', 'Pending Administration Manager Approval'), ('pending_senior_final_approval', 'Pending Senior Customer Service Final Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_senior_approval', max_length=40),
        ),
    ]
