# Generated by Django 4.2.6 on 2023-10-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(choices=[('admin', 'Administration'), ('services', 'Services'), ('production', 'Production'), ('financial', 'Financial')], max_length=20)),
                ('project_reference', models.CharField(max_length=255)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('_status', models.CharField(choices=[('pending_financial_approval', 'Pending Financial Approval'), ('approved', 'Approved')], default='pending_financial_approval', max_length=30)),
            ],
        ),
    ]
