# Generated by Django 4.2.6 on 2023-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_status',
            field=models.CharField(choices=[('pending_subteam_approval', 'Pending Subteam Approval'), ('pending_manager_approval', 'Pending Manager Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending_subteam_approval', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'High'), ('m', 'Medium')], default='m', max_length=1),
        ),
    ]
