# Generated by Django 4.2.6 on 2023-10-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0002_task__status_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='_status',
            field=models.CharField(choices=[('pending_subteam_approval', 'Pending Subteam Approval'), ('pending_manager_approval', 'Pending Manager Approval'), ('approved', 'Approved')], default='pending_subteam_approval', max_length=30),
        ),
    ]
